### ISSUE TITLE
error C is not defined

### ISSUE THREAD

**Issue by jseaman-coax** [bennomeier/faulhaber#4]
On running as a library python issues the error
Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
  File "C:\Users\jseaman\Documents\cardice\mc5005.py", line 127, in getCastedRegister
    return hex(int.from_bytes(C.readRegister(address, subindex = subindex), byteorder='little'))
NameError: name 'C' is not defined

replace
  def getCastedRegister(self, address, subindex = 0):
        return hex(int.from_bytes(C.readRegister(address, subindex = subindex), byteorder='little'))
with
  def getCastedRegister(self, address, subindex = 0):
        return hex(int.from_bytes(self.readRegister(address, subindex = subindex), byteorder='little'))

This will call the current instance of the Controller

**Comment by bennomeier** [comment]
thanks - should be fixed now...
